# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test_print": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hassanmasood1.github.io/nbdev_demo/"

git_url = "https://github.com/hassanmasood1/nbdev_demo/tree/master/"

def custom_doc_links(name): return None
